version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - microservice-net
    volumes:
      - discovery_logs:/app/logs

  departement-service:
    build: ./departement-service
    container_name: departement-service
    ports:
      - "9002:9002"
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    networks:
      - microservice-net
    volumes:
      - departement_data:/app/data
      - departement_logs:/app/logs

  api:
    build: ./api
    container_name: api
    ports:
      - "9000:9000"
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    networks:
      - microservice-net
    volumes:
      - api_data:/app/data
      - api_logs:/app/logs

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    restart: always
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - departement-service
      - api
    networks:
      - microservice-net
    volumes:
      - gateway_logs:/app/logs

networks:
  microservice-net:
    driver: bridge

volumes:
  discovery_logs:
  departement_data:
  departement_logs:
  api_data:
  api_logs:
  gateway_logs:
